name: Smartwin-CI/CD[PROD-Pipeline]

on: 
  workflow_dispatch
#   push:
#     branches:
#       -develop

jobs:
  Fast-FTP-Action:
    name: Fast FTP Action
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fast FTP Action
      uses: anvil-solutions/Fast-FTP-Action@2.1.3
      with:
        server: ${{ secrets.ServerName }}
        port: 2222
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html
