name: Smartwin-CI/CD[PROD-Pipeline]

on: 
  workflow_dispatch
#   push:
#     branches:
#       -develop

jobs:
  Fast-FTP-Action:
    name: Fast FTP Action
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Smartwin - Deploy
      uses: anvil-solutions/Fast-FTP-Action@2.1.3
      with:
        server: ftpupload.net
        username: epiz_32597834
        password: v3BbKIN9GT
        remote_dir: htdocs/test
        cleanup: false
